//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Andreed_IP11.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventsLog
    {
        public int EventID { get; set; }
        public Nullable<int> UserID { get; set; }
        public System.DateTime EventDate { get; set; }
        public string EventDescription { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
