//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Andreed_IP11.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statisticss
    {
        public int StatID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> OrdersCompleted { get; set; }
        public Nullable<decimal> Revenue { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
